name: Build and Deploy App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t aditiapp:${{ steps.vars.outputs.sha_short }} .

      - name: Tag Docker Image
        run: docker tag aditiapp:${{ steps.vars.outputs.sha_short }} aditichauhan20/aditiapp:${{ steps.vars.outputs.sha_short }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: docker push aditichauhan20/aditiapp:${{ steps.vars.outputs.sha_short }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull aditichauhan20/aditiapp:${{ steps.vars.outputs.sha_short }}
            docker stop aditi || true
            docker rm aditi || true
            docker run -d -p 1234:1234 --name aditi aditichauhan20/aditiapp:${{ steps.vars.outputs.sha_short }}
